services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  backend-service:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./db:/app/data
    depends_on:
      - redis

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  core-services:
    build: ./core
    depends_on:
      redis:
        condition: service_started
      backend-service:
        condition: service_healthy

  core-stream-service:
    build: ./livePrice
    ports:
      - "3001:3001"
    depends_on:
      redis:
        condition: service_started
      backend-service:
        condition: service_healthy

  stream-service-fe:
    build: ./price-data-fe
    ports:
      - "3002:3002"
    depends_on:
      redis:
        condition: service_started
      backend-service:
        condition: service_healthy
